---
title: "Neighbourhood Plan Overview"
scctemplate:
  header:
    site_branding: "Suffolk County Council"
  navigation:
    breadcrumb_trail:
      - href: "index.html"
        text: "Neighbourhood Planning Home"
toc: false
---

```{r setup, include = FALSE}
library(httr)
library(XML)
library(dplyr)
library(rvest)
library(leaflet)
library(stringr)
library(here)
library(sf)
library(dplyr)
library(tidyr)
library(purrr)
library(mapview)
library(leafem)
library(leaflet.extras)
library(htmlwidgets)
library(htmltools)
source("get_nps_progress.R")

knitr::opts_chunk$set(echo = TRUE)

# Instructions:
# All you need to edit here is:
  # - The title of your website
  # - The index, make sure you reference all of your pages
  # - OPTIONAL: add an author: or authors: section.
  # - OPTIONAL: add seo descriptions.
```

An overview of which Parishes have completed/submitted neighbourhood plans.

```{r map, echo = FALSE, warning = FALSE, message = FALSE, out.width = "100%", fig.align='center'}
nps <- st_read("Data\\PAR_DEC_2022_EW_BGC.shp", quiet = TRUE)

lkup <- read.csv("Data\\parish_lkup.csv")

lads <- c(
  "West Suffolk",
  "East Suffolk",
  "Mid Suffolk",
  "Babergh"
  # "Breckland",
  # "South Norfolk",
  # "King's Lynn and West Norfolk",
  # "East Cambridgeshire",
  # "South Cambridgeshire",
  # "Colchester",
  # "Braintree",
  # "Broadland",
  # "Great Yarmouth",
  # "Tendring"
)

lkup <- lkup |> 
  filter(LAD22NM %in% lads)

nps <- nps |> 
  filter(PAR22CD %in% lkup$ï..PAR22CD)

lkup <- lkup |> 
  select(PAR22CD = ï..PAR22CD, LAD22NM, LAD22CD)

nps <- left_join(nps, lkup, by = "PAR22CD")

# Combine with nps progress
nps_progress <- get_nps_progress(nps_data)

nps$PAR22NM <- gsub("Campsey Ash", "Campsea Ashe", nps$PAR22NM)
nps$PAR22NM <- gsub("Campsey Ash", "Campsea Ashe", nps$PAR22NM)
nps$PAR22NM <- gsub("Walsham\\-le\\-Willows", "Walsham Le Willows", nps$PAR22NM)
nps$PAR22NM <- gsub("Stoke\\-by\\-Nayland", "Stoke by Nayland", nps$PAR22NM)


# Collection of tidying names
nps_progress$qualifing_body <- gsub("Beccles \\(reviewed \\- Beccles parish only\\)", "Beccles", nps_progress$qualifing_body)
nps_progress$qualifing_body <- gsub("Oulton Broad \\(superceded\\)", "Oulton Broad", nps_progress$qualifing_body)
nps_progress$qualifing_body <- gsub("Rushmere St Andrew", "Rushmere St. Andrew", nps_progress$qualifing_body)
nps_progress$qualifing_body <- gsub("Trimley St Mary", "Trimley St. Mary", nps_progress$qualifing_body)
nps_progress$qualifing_body <- gsub("Capel St Mary", "Capel St. Mary", nps_progress$qualifing_body)
nps_progress$qualifing_body <- gsub("Great Walding Field", "Great Waldingfield", nps_progress$qualifing_body)

nps_progress$qualifing_body <- gsub("Henstead with Hulver St", "Henstead with Hulver Street", nps_progress$qualifing_body)
nps_progress$qualifing_body <- gsub("Wenhaston with Mellis Hamlet", "Wenhaston with Mells Hamlet", nps_progress$qualifing_body)

nps <- left_join(nps, nps_progress, by = c("PAR22NM" = "qualifing_body"))

# Creating URL for each neighbourhood plan, depends on the district
nps$url_name <- tolower(nps$PAR22NM)

nps$url_name <- gsub(" ", "-", nps$url_name)
nps$url_name <- gsub("st\\.", "st", nps$url_name)

nps_list <- lapply(unique(nps$LAD22NM), function(i) {
  
  ld <- nps |> 
    filter(LAD22NM == i)
  
  if(i == "East Suffolk") {
    ld$url <- paste0(
      "https://www.eastsuffolk.gov.uk/planning/neighbourhood-planning/neighbourhood-plans-in-the-area/", ld$url_name, "-neighbourhood-area/"
    )
  } else if(i == "West Suffolk") {
    ld$url <- paste0(
      "https://www.westsuffolk.gov.uk/planning/Planning_Policies/neighbourhood-planning/neighbourhood-planning-in-", ld$url_name, ".cfm"
    )
  } else if (i == "Mid Suffolk") {
    ld$url <- paste0(
      "https://www.midsuffolk.gov.uk/planning/neighbourhood-planning/neighbourhood-planning-in-mid-suffolk/", ld$url_name, "-neighbourhood-plan/"
    )
  } else if (i == "Babergh") {
    ld$url <- paste0(
      "https://www.midsuffolk.gov.uk/planning/neighbourhood-planning/neighbourhood-planning-in-babergh/", ld$url_name, "-neighbourhood-plan/"
    )
  }
  
  return(ld)
  
})

nps <- bind_rows(nps_list)

hexes <- data.frame(
  progress = c(
    "adopted",
    "in progress",
    "not started/no info"
  ),
  hex = c(
    "#00703c",
    "#e8850c",
    "#e2eefa"
  )
)

nps$progress[is.na(nps$progress)] <- "not started/no info"

nps <- left_join(nps, hexes, by = "progress")

nps <- st_transform(nps, 4326)

par_label <- sprintf(
  "<strong>%s</strong><br/>%s<br/> Click for more information.",
  nps$PAR22NM, nps$progress
) %>% lapply(htmltools::HTML)

par_popup <- sprintf(
  "<strong>%s</strong><br/>Click <strong><a href = %s>here</a></strong> for the latest information on this Neighbourhood Plan<br/>",
  nps$PAR22NM, nps$url
) %>% lapply(htmltools::HTML)

nps_map <- leaflet() |> 
  addTiles(group = "Topo") |> 
  addPolygons(
    data = nps,
    group = "Parish",
    color = "black",
    opacity = 1,
    weight = 2,
    fillColor = nps$hex,
    fillOpacity = 0.7,
    highlightOptions = highlightOptions(
      color = "white",
      weight = 4,
      fill = "#666",
      fillOpacity = 0.9,
      bringToFront = TRUE
    ),
    label = par_label,
    labelOptions = labelOptions(
      style = list("font-weigth" = "normal", padding = "3px 8px"),
      textsize = "20px",
      direction = "auto"
    ),
    popup = par_popup,
    popupOptions = popupOptions(
      style = list("font-weigth" = "normal", padding = "3px 8px"),
      textsize = "20px",
      direction = "auto"
    )
  ) |> 
  addLayersControl(
    data = nps,
    overlayGroups = c(
      "Parish"
    ),
    position = "bottomright"
  ) |> 
  addSearchFeatures(
    targetGroups = c("Parish", nps$PAR22NM),
    options = searchFeaturesOptions(
      hideMarkerOnCollapse = TRUE,
      zoom = 12
    )) |> 
  addFullscreenControl()


nps_map
```
